<?php
/*
Plugin Name:  Maera Compressor
Plugin URI:	  http://press.codes
Description:  Minimize HTML when not in development mode. Requires the Maera theme.
Version:      1.0
Author:       Aristeides Stathopoulos
Author URI:   http://press.codes
*/

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Maera_HTML_Minimize {

	function construct() {

		if ( ! class_exists( 'Minify_HTML' ) ) {
			require_once( __DIR__ . '/class-Minify_HTML.php' );
		}

		// If we're not on dev mode, minimize the page HTML.
		$admin_settings = get_option( 'maera_admin_options' );
		if ( ! isset( $admin_settings['dev_mode'] ) || 1 != $admin_settings['dev_mode'] ) {
			add_filter( 'timber_output', array( $this, 'minimize_html' ) );
		}

	}

	/*
	* This uses the Minify_HTML class from https://code.google.com/p/minify/source/browse/min/lib/Minify/HTML.php
	* Reduces some of the whitespace generated by the shells and Timber.
	*/
	function minimize_html( $html ) {

		$options = array( 'xhtml' => true );
		$html = Minify_HTML::minify( $html, $options );

		$html = str_replace( '<a
		', '<a ', $html );
		$html = str_replace( '<ul
		', '<ul ', $html );
		$html = str_replace( '<li
		', '<li ', $html );
		$html = str_replace( '<div
		', '<div ', $html );
		$html = str_replace( '<body
		', '<body ', $html );
		$html = str_replace( '<header
		', '<header ', $html );
		$html = str_replace( '<footer
		', '<footer ', $html );
		$html = str_replace( '<link
		', '<link ', $html );
		$html = str_replace( '<article
		', '<article ', $html );
		$html = str_replace( '<span
		', '<span ', $html );
		$html = str_replace( '<p
		', '<p ', $html );
		$html = str_replace( '
		itemprop="', ' itemprop="', $html );

		return $html;

	}

}
